#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BOARD_COLS 4
#define BOARD_ROWS 4
#define CARD_COUNT (BOARD_COLS * BOARD_ROWS)
#define PAIR_COUNT (CARD_COUNT / 2)
#define TRAP_CARD_COUNT 2
#define TRAP_CARD_VALUE 0
#define TARGET_PAIRS (PAIR_COUNT - (TRAP_CARD_COUNT / 2))

#define CARD_SIZE 96
#define BOARD_PADDING 28
#define WINDOW_WIDTH (BOARD_COLS * CARD_SIZE + BOARD_PADDING * 2)
#define WINDOW_HEIGHT (BOARD_ROWS * CARD_SIZE + BOARD_PADDING * 2 + PANEL_HEIGHT)
#define PANEL_HEIGHT 138

#define FLIP_BACK_SECONDS 0.85f
#define SCORE_PER_PAIR 20
#define TRAP_LIFE_PENALTY 2

#define BEST_SCORE_FILE "best_score.dat"

#endif
